name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas numpy scikit-learn

    # ============================
    # CREATE SQLITE DB FOR MLFLOW
    # ============================
    - name: Prepare MLflow DB
      run: |
        if [ ! -f mlflow.db ]; then
          sqlite3 mlflow.db "VACUUM;"
        fi

    # ============================
    # RUN MODELLING
    # ============================
    - name: Run modelling.py
      env:
        MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
      run: |
        python MLProject/modelling.py

    # ============================
    # GET LATEST RUN_ID FROM DB
    # ============================
    - name: Get MLflow run_id
      env:
        MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
      run: |
        RUN_ID=$(sqlite3 mlflow.db "SELECT run_uuid FROM runs ORDER BY start_time DESC LIMIT 1;")
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest Run ID = $RUN_ID"

    # ============================
    # COMMIT & PUSH mlflow.db
    # ============================
    - name: Commit & push MLflow DB
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add mlflow.db
        git commit -m "Update MLflow tracking DB [skip ci]" || echo "No changes"
        git push origin main

    # ============================
    # BUILD DOCKER IMAGE
    # ============================
    - name: Build Docker Model
      env:
        RUN_ID: ${{ env.RUN_ID }}
      run: |
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name msml_insurance_model

    # ============================
    # PUSH TO DOCKER HUB
    # ============================
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag msml_insurance_model ${{ secrets.DOCKER_HUB_USERNAME }}/msml_insurance_model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/msml_insurance_model:latest
